# Generated by Django 4.1.2 on 2023-08-06 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_concert_concert_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Publication Date'),
        ),
    ]
