# Generated by Django 4.1.2 on 2023-08-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_review_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='date_of_insert',
        ),
        migrations.RemoveField(
            model_name='review',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('1', 'Bad - 1'), ('2', 'Sufficient - 2'), ('3', 'Average - 3'), ('4', 'Good - 4'), ('5', 'Excellent - 5')]),
        ),
    ]
