# Generated by Django 4.1.2 on 2023-08-06 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_alter_player_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='concert_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 21, 33), verbose_name='Date and time'),
        ),
    ]
