# Generated by Django 4.1.2 on 2023-08-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_alter_concert_concert_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('1', 'Bad'), ('2', 'Sufficient'), ('3', 'Average'), ('4', 'Good'), ('5', 'Excellent')], max_length=10),
        ),
    ]
