# Generated by Django 4.1.2 on 2023-08-08 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 8, 11, 12, 52, 291353)),
        ),
    ]
