# Generated by Django 4.1.2 on 2023-08-08 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_review_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 8, 11, 13, 51, 32607, tzinfo=datetime.timezone.utc)),
        ),
    ]
