# Generated by Django 4.1.2 on 2023-08-08 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_alter_review_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
