# Generated by Django 4.1.2 on 2023-08-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_alter_review_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=300),
        ),
    ]
