# Generated by Django 4.1.2 on 2023-08-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_alter_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
