# Generated by Django 4.2.5 on 2023-09-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_alter_concert_concert_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
