# Generated by Django 4.2.5 on 2023-09-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0019_alter_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Surname'),
        ),
    ]
